### PR TITLE
Integrate bindgen

### PR DESCRIPTION
**Pull request by vihanb**
This integrates the bindgen into the main VSL-CLI which formats, validates, and performs other things to aid on the low-level interface provided by bindgen

### CODE REVIEW

**Review by taylorhansen — APPROVED** [review]
Looks good, but I'm not sure if it would be better to just let others use `vsl-bindgen` as a separate command instead of integrating it as a vsl subcommand. If you really want to start bloating the package a bit, though, then that's your call.

**Comment by vihanb** [comment]
@CrazyGuy108 the bindgen itself uses a binary format for receiving options to keep clang happy

**Comment by taylorhansen** [comment]
@vihanb what?? I would think that you could do it all in a `vsl-bindgen ...` command rather than `vsl bindgen ...`, right?

**Comment by vihanb** [comment]
@CrazyGuy108 VSL bindgen does `vsl-bindgen input.h out.vsl <clang opts>` byt opts for vsl-bindgen itself are inputted in format `\0x1F<4 bytes of opt id><4 bytes of opt value len><value>\0x1E`

**Comment by taylorhansen** [comment]
@vihanb that doesn't seem to explain what I'm trying to get at here. Conceptually, `vsl-bindgen ...` should be no different than `vsl bindgen ...` except that there's a space where there was a `-`.

**Comment by vihanb** [comment]
@CrazyGuy108 I guess the names can be confusing but `vsl-bindgen` is C++ and can't interact with the node parts of VSL so vsl-bindgen is mostly a 'helper' utility which outsources some of the work, but for complex things like classes and nested things for C++, we'd need to outsource that to VSL type deductor. There are also certain nodes like function pointers that need to talk to VSL to see if lambda/closure will work along with resolving naming conflicts with other imported libraries and dependencies

**Comment by taylorhansen** [comment]
@vihanb I kinda see what you mean there. I would've preferred a flag like `--bindgen`, e.g. `vsl --bindgen a.cpp -o a.vsl` but I guess what you have now works fine.

**Pull request merged**
