### PR TITLE
feature: registers functions and clean up

### PR DESCRIPTION
**Pull request by vihanb**
This does a lot of things including fixing many many bugs along with
adding function registration. Lookup is not added yet.

### I have:
 - [x] Ran a test (`npm run dev && npm test`)
 - [x] Added tests for my changes
 - [x] Documented my code thoroughly.

### CODE REVIEW

**Comment by taylorhansen** [comment]
This seems like a huge change because of all the formatting. :P Looks good though.

**Comment by taylorhansen** [comment]
Looks good to me, but I'd prefer to have all those formatting changes on their own separate PR just for organization purposes.

**Comment by vihanb** [comment]
@CrazyGuy108 formatting changes?

**Comment by taylorhansen** [comment]
@vihanb What i mean is that when I'm looking at the diff I have to scroll through a lot of files where all that's changed is removal of unnecessary whitespace and adding a newline to the end of some files

**Pull request merged**
