### PR TITLE
feature: Type Deduction & Scope Resolution

### PR DESCRIPTION
**Pull request by vihanb**
This commit will bring type deduction and basic scope resolution. Enough for the ability for really primitive LLVM generation. Generics are a little more complicated and properties/command chains will need to work before I can really work on those

Signed-off-by: Vihan B <contact@vihan.org>

### I have:
 - [x] Ran a test (`npm run dev && npm test`)
 - [ ] Added tests for my changes
 - [x] Documented my code thoroughly.

### CODE REVIEW

**Comment by vihanb** [comment]
@vsl-lang/dev-team if any of you want to mess with this and see if it breaks that would be great because I'm not sure how to exactly write tests for the transformers.

**Review by taylorhansen — APPROVED** [review]
Cool

**Comment by vihanb** [comment]
Okay awesome thing. I am able to resolve thing like:
```swift
func f(n: Double) { ... }
var a = 1
f(n: a)
```
will mean `a` is a double. Though I have one question which this brought up: How do we want to do want to do reflection because I'll have to figure that out and see if I need another pass. An example: Are we going to have an equivilent of C++'s `typeid`? If so this might be a problem because `a`'s type is only resolved at `f(...)`

**Comment by taylorhansen** [comment]
I would deduce the type based on the type of what it's initialized by, so a would be an int since 1 is an int. To get a double you could simply do 1.0. Iirc some compilers already do the automatic conversion between ints and doubles, at least for literals.

**Comment by vihanb** [comment]
@CrazyGuy108 Implicit conversion is definetly a thing that'll be implemeneted but that can't always be done though as casting to a smaller int type can bork

**Pull request closed without merging**
