### PR TITLE
Feature/plane intersection resolution

### PR DESCRIPTION
**Pull request by vihanb**
This does implements plane intersection algorithm for type deduct: https://staging.vihan.org/VSL/docs/class/src/vsl/resolver/typeResolver.js~TypeResolver.html#instance-method-mutableIntersect

### I have:
 - [x] Ran a test (`npm run dev && npm test`)
 - [ ] Added tests for my changes
 - [x] Documented my code thoroughly.

### CODE REVIEW

**Comment by taylorhansen** [comment]
From the docs:
> \(\forall c \in D_3 . c_T \in D_1 \land c_V \in D_2\), where \(c\) is a candidate, \(c_T\) is a root type and \(c_V\) is an applied type.

I would prefer plain english than having to read this. :P

**Comment by vihanb** [comment]
@CrazyGuy108 oh :P don't worry about that, in the docs it's converted from latex to normal maths.

**Comment by taylorhansen** [comment]
@vihanb It looks just like what I quoted on my machine in the actual generated docs in the page you linked

**Comment by vihanb** [comment]
@CrazyGuy108 screenshot? that means your mathjax is borked

**Comment by vihanb** [comment]
screen shot 2017-06-24 at 11 56 53 am
It should like like that

**Comment by taylorhansen** [comment]
screenshot from 2017-06-24 12-10-37
This is what it looks like on my computer.

**Pull request merged**
